name: Go
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  golang-ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: -c .golangci.yaml
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Test
        run: go test -v -count=1 -race ./...
  swag-docs:
    name: swagger-gen
    needs:
      - golang-ci
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Generate Swagger Docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g ./internal/handler/api.go -o docs
      - name: Commit Documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/*
          git commit -m "docs: update swagger documentation [ci skip]" || echo "No changes to commit"
          git pull origin ${{ github.head_ref }} --rebase
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
